//
//  DashboardModels.swift
//  CoFi
//
//  Created by Santo Michael Sihombing on 12/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct Upcoming {
    let itemName: String
    let price: Int
    let date: Date
    let reminderTime: String
    let icon: String
    let iconColor: String
    let bgColor: String
}
