//
//  TransactionModels.swift
//  CoFi
//
//  Created by Santo Michael Sihombing on 12/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Transaction {
    let name: String
    let date: Date
    let totalPrice: Int
    let items: [Item]
}

struct Item {
    let name: String
    let amount: Int
    let price: Int
    let person: String
}
